export const products = [
  {
    _id: "1",
    name: "samsung galaxy",
    category: { _id: "1", name: "mobiles" },
    price: 10000,
    isAvailable: true,
  },
  {
    _id: "2",
    name: "samsung galaxy s1",
    category: { _id: "1", name: "mobiles" },
    price: 15000,
    isAvailable: true,
  },
  {
    _id: "3",
    name: "google pixel",
    category: { _id: "1", name: "mobiles" },
    price: 30000,
    isAvailable: true,
  },
  {
    _id: "4",
    name: "apple iphone 6s",
    category: { _id: "1", name: "mobiles" },
    price: 40000,
    isAvailable: true,
  },
  {
    _id: "5",
    name: "samsung galaxy s7",
    category: { _id: "1", name: "mobiles" },
    price: 50000,
    isAvailable: true,
  },
  {
    _id: "6",
    name: "hp spectre",
    category: { _id: "2", name: "laptops" },
    price: 80000,
    isAvailable: true,
  },
  {
    _id: "7",
    name: "lenovo ideapad",
    category: { _id: "2", name: "laptops" },
    price: 60000,
    isAvailable: true,
  },
  {
    _id: "8",
    name: "acer predator",
    category: { _id: "2", name: "laptops" },
    price: 100000,
    isAvailable: true,
  },
  {
    _id: "9",
    name: "apple macbook",
    category: { _id: "2", name: "laptops" },
    price: 60000,
    isAvailable: true,
  },
  {
    _id: "10",
    name: "hp br001",
    category: { _id: "2", name: "laptops" },
    price: 70000,
    isAvailable: true,
  },
];
